name: tests
on:
  push:
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.40.1
          # skip-pkg-cache: true
          # skip-build-cache: true

  gotest:
    name: unit-test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16.1"
      - name: Install CLI
        run: |
          go install
      - name: Go Test
        run: |
          go test ./cmd -v
